<?php

namespace ContainerVaWWc3l;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WDCSOZWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wDCSOZW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wDCSOZW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'eventDispatcher' => '?',
            'tokenStorage' => '?',
            'urlGenerator' => '?',
        ]);
    }
}
