<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBi2x9eA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBi2x9eA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBi2x9eA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBi2x9eA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBi2x9eA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bi2x9eA',
    'container.build_id' => 'dba03e55',
    'container.build_time' => 1694241577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBi2x9eA');
